openapi: 3.0.0
info:
  title: Kiwi Promocode Update API
  version: '1.0'
  description: "Update or replace an existing kiwi.com promotional code along with its associated information. Associated information includes the booking ID, reasons for promotional code's creation (issues with a previous booking), if the promotional code was used, the amount (in euro) that the promotional code covers, as well as the email account details of promotional code's user. **Note**: The Kiwi Promocode Update API is only accessible (via https) to authorized users. **Note**: This API connects directly to the kiwi.com backend; consequently, the Kiwi team recommends that you only use this API to interact with our promotional codes. **Note**: This API does not apply to new promotional codes; moreover, parameters with null values may not get passed to the API.   "
  contact:
    name: Kiwi Support
    url: 'https://kiwi.com/api'
    email: email@kiwi.com
  termsOfService: 'https://kiwi.com/terms'
  license:
    name: Apache 2.0
    url: 'https://kiwi.com/price'
servers:
  - url: 'http://promocodes.kiwi.com'
    description: Promocodes
paths:
  /promocode:
    put:
      summary: PUT promocode
      operationId: put-promocode
      responses:
        '200':
          description: OK
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: AAAAQ
                    description: "The promocode's unique alphanumeric code"
                  bid:
                    type: integer
                    example: 123654
                    description: The booking ID
                  used:
                    type: boolean
                    example: 'false'
                    description: "The status of promocode's use"
                  amount:
                    type: integer
                    example: 152
                    description: The amount in euro the promcode covers
                  email:
                    type: string
                    example: joansmyth@email.com
                    description: Email details of promocode user
                required:
                  - code
                  - bid
                  - used
                  - amount
                  - email
              examples:
                Schema Example:
                  value:
                    promocodes:
                      - code: AAAAQ
                        bid: null
                        used: false
                        amount: 152
                        email: joansmyth@email.com
      description: "Update or replace a kiwi.com promocode along with its additional information. Additional information includes the booking ID, the reasons for the promocode's creation, if it was used, the amount (€) the promocode covers, as well as the email account details of promocode's user.  "
      tags:
        - Promocode endpoints
      parameters:
        - schema:
            type: string
          in: query
          name: code
          description: '**Code**. Search by unique alphnumeric code. *Example: AAAAQ*. '
          required: true
        - schema:
            type: integer
          in: query
          name: bid
          description: '**Bid**. Calls the booking ID (*Example: 203589*).  '
          required: true
        - schema:
            type: boolean
          in: query
          name: used
          description: '**Used**. If *true*, the promocode has been used.'
          required: true
        - schema:
            type: integer
          in: query
          name: amount
          description: '**Amount**. Calls the monetary amount in euro that the promocode covers. *Example: 450.00*   '
          required: true
        - schema:
            type: string
          in: query
          name: email
          description: '**Email**. Calls the email details of promocode users. *Example: joansmyth@email.com*.  '
          required: true
      security:
        - app_id: []
components:
  schemas: {}
  securitySchemes:
    app_id:
      type: http
      scheme: oauth
      description: Access is available to authorized users via http.
